# Generated by Django 5.1.15 on 2026-10-04 08:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("ISSUE_CREATED", "New issue"),
                            ("ISSUE_ASSIGNED", "Assigned to you"),
                            ("ISSUE_TAGGED", "Tagged on an issue"),
                            ("ISSUE_STATUS", "Status changed"),
                            ("ISSUE_UPDATE", "New update"),
                            ("ISSUE_REMARK", "New remark"),
                            ("ISSUE_ESCALATED", "Escalated to President"),
                            ("ISSUE_REOPENED", "Issue reopened"),
                            ("ISSUE_OVERDUE", "Issue overdue"),
                            ("COSA_POST", "COSA update"),
                            ("EVENT", "Event"),
                            ("COMMITTEE", "Committee"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("message", models.CharField(blank=True, max_length=300)),
                ("target_type", models.CharField(blank=True, max_length=20)),
                ("target_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_read", "-created_at"],
                        name="notificatio_recipie_684eac_idx",
                    ),
                    models.Index(
                        fields=["recipient", "-created_at"],
                        name="notificatio_recipie_a972ce_idx",
                    ),
                ],
            },
        ),
    ]
