# Generated by Django 5.1.15 on 2026-10-04 08:07

import apps.cosa.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_initial"),
        ("issues", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("CULTURAL", "Cultural"),
                            ("TECHNICAL", "Technical"),
                            ("SPORTS", "Sports"),
                            ("LITERARY", "Literary"),
                            ("SOCIAL", "Social"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True, max_length=2000)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to=apps.cosa.models.club_logo_path
                    ),
                ),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "secretary_role",
                    models.ForeignKey(
                        blank=True,
                        help_text="COSA secretary the club reports to, e.g. Cultural or SciTech.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clubs",
                        to="accounts.rolemailbox",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ClubMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("HEAD", "Head"),
                            ("COORDINATOR", "Coordinator"),
                            ("MEMBER", "Member"),
                        ],
                        default="MEMBER",
                        max_length=11,
                    ),
                ),
                ("joined_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="cosa.club",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="club_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="club",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                related_name="clubs",
                through="cosa.ClubMembership",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Committee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("purpose", models.TextField(blank=True, max_length=2000)),
                (
                    "formed_on",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                (
                    "applications_open_until",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_committees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="committees",
                        to="issues.issue",
                    ),
                ),
            ],
            options={
                "ordering": ["-formed_on", "name"],
            },
        ),
        migrations.CreateModel(
            name="CommitteeApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("statement", models.TextField(max_length=1000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=8,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="committee_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "committee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="cosa.committee",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CommitteeMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("HEAD", "Head"),
                            ("COORDINATOR", "Coordinator"),
                            ("MEMBER", "Member"),
                        ],
                        default="MEMBER",
                        max_length=11,
                    ),
                ),
                ("added_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "added_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "committee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="cosa.committee",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="committee_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["position", "added_at"],
            },
        ),
        migrations.CreateModel(
            name="CosaPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("body", models.TextField(max_length=2000)),
                (
                    "attachment",
                    models.FileField(
                        blank=True, null=True, upload_to=apps.cosa.models.post_file_path
                    ),
                ),
                ("author_role", models.CharField(blank=True, max_length=80)),
                ("is_pinned", models.BooleanField(default=False)),
                ("is_archived", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cosa_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posts",
                        to="issues.category",
                    ),
                ),
                (
                    "linked_issues",
                    models.ManyToManyField(
                        blank=True, related_name="posts", to="issues.issue"
                    ),
                ),
            ],
            options={
                "ordering": ["-is_pinned", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                (
                    "organising_body",
                    models.CharField(
                        blank=True,
                        help_text="If not a club, e.g. 'COSA'.",
                        max_length=120,
                    ),
                ),
                ("description", models.TextField(blank=True, max_length=4000)),
                ("venue", models.CharField(blank=True, max_length=150)),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                (
                    "poster",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.cosa.models.event_poster_path,
                    ),
                ),
                ("registration_url", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="SCHEDULED",
                        max_length=9,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "club",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="cosa.club",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["starts_at"],
            },
        ),
        migrations.AddField(
            model_name="committee",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="committees",
                to="cosa.event",
            ),
        ),
        migrations.AddConstraint(
            model_name="clubmembership",
            constraint=models.UniqueConstraint(
                fields=("club", "user"), name="uniq_club_member"
            ),
        ),
        migrations.AddConstraint(
            model_name="committeeapplication",
            constraint=models.UniqueConstraint(
                fields=("committee", "applicant"), name="uniq_committee_application"
            ),
        ),
        migrations.AddConstraint(
            model_name="committeemember",
            constraint=models.UniqueConstraint(
                fields=("committee", "user"), name="uniq_committee_member"
            ),
        ),
        migrations.AddIndex(
            model_name="cosapost",
            index=models.Index(
                fields=["is_archived", "-is_pinned", "-created_at"],
                name="cosa_cosapo_is_arch_ca99f1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["status", "starts_at"], name="cosa_event_status_39b490_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["club", "starts_at"], name="cosa_event_club_id_b31567_idx"
            ),
        ),
    ]
