# Generated by Django 5.1.15 on 2026-10-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="issueupvote",
            name="is_private",
            field=models.BooleanField(default=False),
        ),
    ]
