# Generated by Django 5.1.15 on 2026-10-04 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("issues", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rolemailbox",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Issues in this category are auto-assigned to this role.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="role_mailboxes",
                to="issues.category",
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["user_type"], name="accounts_us_user_ty_b6cfc8_idx"
            ),
        ),
    ]
