# Generated by Django 5.1.15 on 2026-10-04 14:18

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="about",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="user",
            name="batch_year",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="Year of joining, e.g. 2023", null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="branch",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CSE", "Computer Science and Engineering"),
                    ("MNC", "Mathematics and Computing"),
                    ("AIDS", "Artificial Intelligence and Data Science"),
                ],
                max_length=4,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to=apps.accounts.models.profile_photo_path
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="semester",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="Current semester, 1-8", null=True
            ),
        ),
    ]
